#pragma once

// GENERATED by Tools/units/gen_units.py

namespace enh::dsp::units
{
    inline constexpr int count = 33;
    inline constexpr int firstParam = 62, numParams = 217;
    inline constexpr int firstUnit = 17;
    struct Info { const char* key; const char* name; int firstParam, numParams, heightU; };
    inline constexpr Info info[count] {
        { "shimmer", "SHIMMER", 62, 8, 2 },
        { "plate", "PLATE 140", 70, 6, 1 },
        { "spring", "SPRING TANK", 76, 6, 1 },
        { "grain", "GRAIN CLOUD", 82, 8, 2 },
        { "tape", "ATR TAPE", 90, 8, 2 },
        { "opto", "T4 OPTO", 98, 6, 1 },
        { "varimu", "VARI-MU", 104, 7, 2 },
        { "dyneq", "DYNAMIC EQ 4", 111, 13, 2 },
        { "shuffler", "SHUFFLER", 124, 7, 1 },
        { "rotator", "PHASE ROTATOR", 131, 4, 1 },
        { "bode", "BODE SHIFTER", 135, 5, 1 },
        { "harm", "HARMONIZER", 140, 7, 2 },
        { "bbd", "BBD ENSEMBLE", 147, 6, 1 },
        { "vocoder", "ROBOVOX", 153, 6, 2 },
        { "submaxx", "SUBMAXX", 159, 5, 1 },
        { "clip", "OVERCLIP", 164, 6, 1 },
        { "deharsh", "DE-HARSH", 170, 8, 1 },
        { "maximizer", "882i", 178, 4, 1 },
        { "rayroom", "RAY ROOM", 182, 6, 3 },
        { "vinyl", "VINYL DECK", 188, 7, 3 },
        { "rotary", "ROTARY CAB", 195, 6, 3 },
        { "cassette", "CASSETTE DECK", 201, 8, 3 },
        { "tapeecho", "TAPE ECHO", 209, 7, 3 },
        { "valveamp", "VALVE AMP", 216, 7, 3 },
        { "speakercab", "SPEAKER CAB", 223, 6, 3 },
        { "radio", "RADIO", 229, 7, 3 },
        { "pendulum", "PENDULUM", 236, 7, 3 },
        { "bounce", "BOUNCE DELAY", 243, 6, 3 },
        { "sympathy", "SYMPATHY", 249, 6, 3 },
        { "flyby", "FLYBY", 255, 6, 3 },
        { "tesla", "TESLA COIL", 261, 6, 3 },
        { "talkbox", "TALK BOX", 267, 6, 3 },
        { "lavalamp", "LAVA LAMP", 273, 6, 3 },
    };
}
