#!/usr/bin/env python3
"""The website's 3D views as plain scripts: docs/rack3d.bundle.js (the home page's rack) and
docs/designer3d.bundle.js (the Unit Designer's 3D view).

rack3d.js is written as an ES module (it imports three.js and rack3d-data.js). Browsers refuse modules on a
page opened as a file (file://), so the rack would not show there. This joins the three into one ordinary
script that works both served and opened as a file:
  - three.js in its own function scope, handing back the names rack3d.js uses;
  - rack3d-data.js and rack3d.js with their import/export lines turned into plain declarations;
  - the unit art (img/units/*.svg) inside it, used only on a page opened as a file (canvases drawn from
    file:// images are 'tainted' and WebGL refuses them; the same art as data: URLs is not).
Run after editing rack3d.js, rack3d-data.js or the unit art; then scripts/stamp-site.py.
"""

import json, os, re

DOCS = os.path.join (os.path.dirname (os.path.dirname (os.path.abspath (__file__))), "docs")
read = lambda p: open (os.path.join (DOCS, p), encoding = "utf-8").read ()

def three_scope ():
    """three.js in a function returning its exported names (and those names)."""
    three = read ("vendor/three/three.module.min.js")
    at = three.rindex ("export{")
    names = []
    for item in three[at + len ("export{"): three.index ("}", at)].split (","):
        parts = item.strip ().split (" as ")
        names.append ((parts[0].strip (), (parts[1] if len (parts) > 1 else parts[0]).strip ()))
    return three[:at] + "return {" + ",".join (f"{name}:{local}" for local, name in names) + "};", { n for _, n in names }

def unimport (src, exported):
    """A module's `import {...} from three` as a plain `const {...} = THREE;`."""
    imp = re.search (r"import \{([^}]*)\} from \"\./vendor/three/three\.module\.min\.js\";\n", src)
    used = [n.strip () for n in imp.group (1).split (",") if n.strip ()]
    missing = [n for n in used if n not in exported]
    if missing: raise SystemExit ("three.module.min.js does not export: " + ", ".join (missing))
    return src.replace (imp.group (0), "const { " + ", ".join (used) + " } = THREE;\n", 1), len (used)

def write (name, three, body, note):
    out = ("/* ENH Master site: " + note + ", as one plain script - GENERATED by scripts/make-rack3d-bundle.py from\n"
           "   vendor/three/three.module.min.js (three.js, MIT: see vendor/three/LICENSE) and the files named below.\n"
           "   Edit those, not this. */\n"
           "(function () {\n\"use strict\";\n"
           "const THREE = (function () {\n" + three + "\n}) ();\n" + body + "\n}) ();\n")
    open (os.path.join (DOCS, name), "w", encoding = "utf-8").write (out)
    return len (out)

def main ():
    three, exported = three_scope ()
    # the home page's rack: rack3d-data.js + rack3d.js, and the unit art
    data = read ("rack3d-data.js").replace ("export const PARTS", "const PARTS", 1)
    rack, used = unimport (read ("rack3d.js"), exported)
    rack = rack.replace ('import { PARTS } from "./rack3d-data.js";\n', "", 1)
    if re.search (r"^\s*(import|export)\b", rack, re.M): raise SystemExit ("rack3d.js has another import/export: teach this script")
    art = {}
    folder = os.path.join (DOCS, "img", "units")
    for f in sorted (os.listdir (folder)):
        if f.endswith (".svg"): art[f[:-4]] = open (os.path.join (folder, f), encoding = "utf-8").read ()
    size = write ("rack3d.bundle.js", three, "const ENH_ART = " + json.dumps (art, ensure_ascii = False, separators = (",", ":")) + ";\n/* rack3d-data.js */\n" + data + "\n/* rack3d.js */\n" + rack, "the 3D rack")
    print (f"rack3d.bundle.js: {size / 1024:.0f} KB ({used} three.js names, {len (art)} pictures)")
    # the Unit Designer's 3D view: designer3d.js
    d3, used = unimport (read ("designer3d.js"), exported)
    if re.search (r"^\s*(import|export)\b", d3, re.M): raise SystemExit ("designer3d.js has another import/export: teach this script")
    size = write ("designer3d.bundle.js", three, "/* designer3d.js */\n" + d3, "the Unit Designer's 3D view")
    print (f"designer3d.bundle.js: {size / 1024:.0f} KB ({used} three.js names)")

if __name__ == "__main__":
    main ()
